spring.application.name=wellington

# Configuracoes de Integracao com a IA (Google Gemini)
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
gemini.api.key= AIzaSyAVF6SF7fNk3KYZsdxxmin48AZVuj7E-G8

spring.kafka.bootstrap-servers=localhost:9092
# Um ID para o seu produtor
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

