spring.application.name=wellington

# Configuracoes de Integracao com a IA (Google Gemini)
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
gemini.api.key= AIzaSyA56GK4g3X9nU3-psDPZZ4busgdsUqec34

server.port=8081
